name: connect

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master

      - name: Connect to the actuated SSH gateway
        uses: alexellis/actuated-ssh-gateway-action@master
        with:
          gatewayaddr: ${{ secrets.SSH_GATEWAY_IP }}
          secure: true

      - name: Setup a tmux session and block until done.
        run: |
          cat << EOF | sudo tee /etc/motd
          ╺┳┓┏━╸┏┓ ╻ ╻┏━╸   ┏━┓┏━╸┏━┓┏━┓╻┏━┓┏┓╻
           ┃┃┣╸ ┣┻┓┃ ┃┃╺┓   ┗━┓┣╸ ┗━┓┗━┓┃┃ ┃┃┗┫
          ╺┻┛┗━╸┗━┛┗━┛┗━┛   ┗━┛┗━╸┗━┛┗━┛╹┗━┛╹ ╹
          To attach to the debug session, run "tmux attach".
          Finally, when you're done, exit the session or type in
          "exit" to let the runner exit.
          EOF
          tmux new-session -d -s debug
          
          # Blocks until someone has attached to the session and closed it
          tmux wait-for channel
